<div class="content-page" ng-controller="DefaultCtrl">

            <!-- Start content -->
            <div class="content">

                <div class="container-fluid">

                    <div class="row">
                        <div class="col-xl-12">
                            <div class="breadcrumb-holder">
                                <h1 class="main-title float-left"><?php echo $Title;  ?></h1>
                                <ol class="breadcrumb float-right">
                                    <li class=""><?php echo $_SERVER['REQUEST_URI']; ?></li>
                                    
                                </ol>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>



                    <div class="row">

                        <div class="col-12">

                            <div class="card mb-3">
                                <div class="card-header">
                                     <span class="pull-right">
                                       
                                    </span>
                                    
                                    <h3>
                                        <i class="far fa-copy"></i> <?php  echo $Title;  ?></h3>

                                </div>

                                <div class="card-body">
                                      <div class="table-responsive">
										            <div class="form-group col-md-3">
                <label for="Exam" >From</label>
                  <input class="form-control" id="Month" ng-model="Month.ThisMonth" autocomplete="off" name="Month" />
                      
            </div>
            <div class="form-group col-md-3">
                <label for="Exam" >To</label>
                  <input class="form-control" id="MonthTo" ng-model="Month.ToMonth" autocomplete="off" name="ToMonth" ng-change="GetCurrentStatusReport()" />
                      
            </div>
            <div col-md-3>
                 <img id="LoadingID" src="<?php echo base_url('dist/img/loading2.gif') ?>" style="display:none; "/ >
            </div>
            <div class="col-md-12 ">
                <span class="fa fa-print" id='printDuration' style="cursor: pointer;"  ></span>
               
                <a href="javascript: genPdf()"> PDF</a>
            </div>
            
          
            
        <div class="col-md-12 myPrintDuration" id="HTMLtoPDF" ng-show="Show==1">
         
                    <h2 style="text-align: center;"> Bangladesh Computer Council</h1>         
                     <h3 style="text-align: center; padding-top:0px; margin-top:-5px;"> Information and communication Technology Division</h3>
                    <h4 style="text-align: center;">Regional Office , Barishal.</h4> <hr>
        <h5 style="text-align:center;"><b>  Report ( Current Status   </b>) <br>within   {{Month.ThisMonth}} to {{Month.ToMonth}} </h5>
        <table class="table table-striped">
            <tr>
                <th>SN</th>
                <th>Course Title  ( Batch No )  </th> 
                 <th> Type </th> 
                 <th>Duration <br/> (hrs) </th>
                 <th>Start - End </th>
                 <th>Organized </th>
                  <th> M </th>
                   <th> F </th>
                  <th> Total </th>
                   <th>Status </th>
               
            </tr>
            <tr ng-repeat="Batch in AllBatch.result">
              
                <td>{{$index + 1}} </td>
                <td style="">{{Batch.CourseTitleName}} ( {{Batch.Batch}} ) </td>
                 <td>{{Batch.TypeName}} </td>
                 <td>{{Batch.DurationHour}} </td>
                 <td>{{Batch.StartDate}} to {{Batch.EndDate}} </td>
                 <td>{{Batch.OrganizationName}} </td>
                  <td>{{Batch.Male}} </td>
                  <td>{{Batch.Female}} </td>
                   <td>{{Batch.studentNumber}} </td>
                 
                   <td>{{Batch.Status}} </td>
                
            </tr>
             <tr>
                <td></td>
                <td ></td> </td>
                 <td> </td>
                 <td></td>
                 <td> </td>
                 <td> Total </td>
                  <td> {{AllBatch.resultTotal.Male}}</td>
                  <td> {{AllBatch.resultTotal.Female}}</td>
                   <td> {{AllBatch.resultTotal.Total}} </td>
                 
                   <td> </td>
                
            </tr>
        </table>
        <br><br>
        <p style="text-align:Right;">N.T: Auto Generated by BCC System</p>
        
        </div>
																
									</div>
                                </div>

                            </div>

                        </div>


                    </div>
                    <!-- end row -->


    <!--List of QusetionType-->


    <!-- Add Modal -->
   
    <!--modal end-->

</div>
</div>
</div>
</body>
</html>

<script type="text/javascript">

  

    app.controller("DefaultCtrl", ["$scope", "$http",
        function ($scope, $http) {
            init();
            function init() {
                initialize();
             
            }
            function initialize() {
                $scope.AllBatch = [];
              
                $scope.Batch = {};
                $scope.Month={};
                $scope.Show=0;
                $scope.reset=reset;
                
                $scope.GetCurrentStatusReport=GetCurrentStatusReport;
                
               
            }
            
            
            function GetCurrentStatusReport(){
                
                $("#LoadingID").css("display", "block");
                
                var MonthFrom=$scope.Month.ThisMonth;
                var MonthTo=$scope.Month.ToMonth;
               
                console.log(MonthFrom+" "+ MonthTo);
              
                
                $scope.AllBatch = [];
                $http({
                    method: 'GET',
                    url: baseUrl + 'Report/GetCurrentStatusReport/'+MonthFrom+'/'+MonthTo
                }).then(function successCallback(response) {
                    $scope.Show=1;
                     
                     
                    $scope.AllBatch = response.data;
                     $("#LoadingID").css("display", "none");
                   console.log($scope.AllBatch);
                }, function errorCallback(response) {
                     $("#LoadingID").css("display", "none");
                });
            }

            

           
            
            function reset()
            {
                $scope.Batch = {};
            }

        }]);
        
        
        function genPdf()
               {
                  
                   
                   html2canvas(document.getElementById("HTMLtoPDF")).then(function(canvas) {
                var img = canvas.toDataURL('image/png');
                var doc = new jsPDF();
                
                var doc = new jsPDF("p", "mm", "a4");
               
                doc.addImage(img, 'JPEG', 0, 0);
                doc.save('test.pdf');
            });
                   
               }

                $(function () {
                    $("#Month").datepicker({
                        dateFormat: 'yy-mm-dd',
                        changeMonth: true,
                        changeYear: true,
                        yearRange: '-100y:c+nn',
                        maxDate: '+365d'
                    });
                });
                
                $(function () {
                    $("#MonthTo").datepicker({
                        dateFormat: 'yy-mm-dd',
                        changeMonth: true,
                        changeYear: true,
                        yearRange: '-100y:c+nn',
                        maxDate: '+365d'
                    });
                });
                
    $(function () {
        $('#printDuration').on('click', function () {
            $.print(".myPrintDuration");
        });
    });
       $(function () {
        $('#printBatch').on('click', function () {
            $.print(".myPrintBatch");
        });
    });
        
</script>